print("This file was created within RStudio")
print("And now it lives on GitHub")
getwd()
g<-read.csv(file="C:/Users/admin/Desktop/2022 Project/Survival_Analysis/Simulated HF mort data for GMPH.csv")
dim(g)
head(g)
